#! /bin/bash

current=`pwd`
dir4=Inst_Custom-Framework.f

    cd $dir4
	echo "  ____________________________________________________________________________ "
	echo " |                                  NOTA:                                     |"
	echo " | Introduce las APK: framework-res.apk, twframework-res.apk y SystemUI.apk,  |"
	echo " | en la ruta : /Tools/CustomFrame.                                           |"
	echo " |____________________________________________________________________________|"
	echo
	if [[ -f twframework-res.apk ]]; then
	echo 
	    echo "Custom twframework-res.apk found."
#		localMode="true"
	else
	   echo -e " \e[1;31mERROR.\e[0m  Custom twframework-res.apk no found."
	fi

	if [[ -f twframework-res.apk ]]; then
#		if [[ $localMode == "true" ]]; then
			echo
			printf "Install twframework-res.apk (\e[1;37mY\e[0m/\e[1;31mN\e[0m)? "
		read INPUT
		if [[ x$INPUT == "xy" || x$INPUT == "xY" || x$INPUT == "x" ]]; then
	           echo
	           cd ../Tools
		java -jar apktool.jar if ../$dir4/twframework-res.apk
		    echo
		echo "--((twframework-res.apk installed))--"
		  else
		      echo "  Installation Canceled"
 fi
 fi
# fi
